<a href="https://colab.research.google.com/github/zajcnataliya/Probability-and-Statistics/blob/main/dz8_%D0%9A%D0%BE%D1%80%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy

Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.


In [10]:
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt

In [12]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [14]:
cov = np.mean(zp*ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

In [23]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [21]:
#рассчитаем коэффициент корреляции Пирсона через несмещенную ковариацию
np.cov(zp, ks, ddof = 1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [17]:
np.std(zp, ddof = 1)

62.31318747531162

In [18]:
np.std(ks, ddof = 1)

183.99544076477068

In [20]:
r = 10175.37777778/(62.31318747531162*183.99544076477068)
r

0.88749009207411

In [22]:
#рассчитаем коэффициент корреляции Пирсона через смещенную ковариацию
np.cov(zp, ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [24]:
np.std(zp, ddof = 0)

59.115480206118605

In [25]:
np.std(ks, ddof = 0)

174.55340157098058

In [26]:
r = 9157.84/(59.115480206118605*174.55340157098058)
r

0.8874900920739162

In [27]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2) Измерены значения IQ выборки студентов,

обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [28]:
import numpy as np
import pandas as pd
from scipy import stats

In [30]:
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
alfa = 0.95

In [31]:
len(x)

10

In [32]:
# Распределение Стьюдента зависит от степеней свободы (n - 1).
# Мы строим 95% интервал. Т.е. α/2  = 0.025
alfa = 0.05 # 0.05/2=0.025, 1-0.025 = 0.975
t = stats.t.ppf(0.975, 10-1) # критерий Стьюдента
t

2.2621571627409915

In [33]:
D = np.var(x, ddof=1) # несмещенная дисперсия
D

111.21111111111111

In [35]:
int_verh = np.mean(x) + t*np.sqrt(D/10)
int_niz = np.mean(x) - t*np.sqrt(D/10)
print(f'[{int_niz}; {int_verh}]')

[110.55608365158724; 125.64391634841274]


3) Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [39]:
sigma = 5
n = 27
M = 174.2

alfa =0.05  # 1-0.95=0.05/2=0.025, 1-0.025 = 0.975
z = stats.norm.ppf(0.975)
z

1.959963984540054

In [40]:
int_verh = M + z*sigma/np.sqrt(n)
int_niz = M - z*sigma/np.sqrt(n)
print(f'[{int_niz}; {int_verh}]')

[172.3140237765397; 176.08597622346028]
